### ISSUE TITLE
Can't get the program to work

### ISSUE THREAD

**Issue by fourjacks** [Graeme22/tastypl#1]
I retraced my steps and re-read the directions. Cloned the repository, installed the dependencies. Went to the "History" tab then "Transactions." Did the custom date range, scrolled to the bottom as instructed, and exported to CSV. 

But still getting errors. Most recent one:

> 

"F0304 22:41:51.352941 9360 tastypl.go:1575] CSV seems malformed
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000070700, 0xc000246d20, 0x43, 0x93)..."

I am on Windows. Other than that nothing out of the ordinary.

For reference here is the thread from the original repository: 
[https://github.com/gotasty/tastypl/issues/4#issuecomment-790269250]

Thanks for any further help to troubleshoot the issue.

**Comment by Graeme22** [comment]
Hi @fourjacks, any chance I could see the full error message instead of just part of it? Also, did you ever open the CSV file in Excel? It tends to corrupt the file.
