### ISSUE TITLE
System cannot find csv file

### ISSUE THREAD

**Issue by jonfaiella** [Graeme22/tastypl#2]
Hello,

Upon executing the program, I receive the error "The system cannot find the file specified". I have tried placing the file in numerous locations. My command prompt shows my location as C:\Users\ (MyName) - so this is where I put the file. Should it be placed elsewhere?

**Comment by Graeme22** [comment]
So it should work if you run the command from the same directory as the file is in. If that doesn't work, it might be a Windows thing? Try specifying the full path, so instead of `-input transactions.csv` do `-input C:\Users\jon\...\transactions.csv` and see if that works.

**Comment by jonfaiella** [comment]
I had already tried that, and it also does not work.

**Comment by jonfaiella** [comment]
The full error message is: "CreateFile tastypl.go: The system cannot find the file specified."

**Comment by Graeme22** [comment]
Ah, so the problem isn't the csv file, it's the go file. You need to either place the `tastypl.go` file in the directory you're running in, or add the go file to your PATH environment variable.

**Comment by jonfaiella** [comment]
Great, so that got it to run! But I'm not sure if it worked? I don't see a chart or a new file created in that directory. This is the command prompt output:

C:\Users\Jon>go run tastypl.go -input transactions.csv -printpl -positions -chart
F0315 19:25:54.858659   32984 tastypl.go:331] can't convert -- to decimal
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc00007a800, 0xc000123cc0, 0x4a, 0x9b)
        C:/Users/Jon/go/src/github.com/golang/glog/glog.go:769 +0xbf
github.com/golang/glog.(*loggingT).output(0x1011d80, 0xc000000003, 0xc000262070, 0xf0a8c1, 0xa, 0x14b, 0x0)
        C:/Users/Jon/go/src/github.com/golang/glog/glog.go:720 +0x39a
github.com/golang/glog.(*loggingT).printDepth(0x1011d80, 0x3, 0x1, 0xc00010fa50, 0x1, 0x1)
        C:/Users/Jon/go/src/github.com/golang/glog/glog.go:646 +0x130
github.com/golang/glog.(*loggingT).print(...)
        C:/Users/Jon/go/src/github.com/golang/glog/glog.go:637
github.com/golang/glog.Fatal(...)
        C:/Users/Jon/go/src/github.com/golang/glog/glog.go:1128
main.parseDecimal(0xc0000164f4, 0x2, 0xc000042ea0, 0xfffffffe)
        C:/Users/Jon Faiella/tastypl.go:331 +0x107
main.(*portfolio).parseTransaction(0xc000068140, 0x0, 0xc00025fc20, 0x11, 0x11, 0xc00010fd4e, 0x1012120)
        C:/Users/Jon Faiella/tastypl.go:594 +0x165
main.(*portfolio).parseTransactions(0xc000068140, 0xc00015b018, 0x165, 0x1ff, 0x1000)
        C:/Users/Jon/tastypl.go:564 +0xf2
main.NewPortfolio(0xc00015b018, 0x165, 0x1ff, 0x0, 0x200)
        C:/Users/Jon/tastypl.go:417 +0x1f0
main.main()
        C:/Users/Jon/tastypl.go:1578 +0x48f
exit status 255

**Comment by Graeme22** [comment]
The format of the csv files has changed since this program was written, so it expects number in the fields containing `--`. Open up the csv file in a non-Excel editor and replace all the `--`s with `0`. That should fix it.

**Comment by Graeme22** [comment]
Also, I am currently rewriting the entire program in Python, which should fix a lot of the common issues and will be a lot easier to use, so stay tuned for that.

**Comment by jonfaiella** [comment]
Thanks so much, that fixed it!
